---
apiVersion: v1
kind: Service
metadata:
    name: jenkins-deployment
    namespace: jenkins-deployment
spec:
    ports:
     - name: http 
       nodePort: 30600
       port : 80
       protocol: TCP
       targetPort: 80
    selector:
       app: jenkins
    type: NodePort 
